[tool.poetry]
name = "rpgpt"
version = "0.1.0"
description = ""
authors = ["Axel Grubba <admin@axelgrubba.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
