# Generated by Django 4.2.1 on 2023-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ece', max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('environment_description', models.TextField()),
                ('weather', models.CharField(max_length=200)),
                ('chosen_actions', models.JSONField()),
                ('outcome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ManyToManyField(related_name='story', to='rpgpt.character')),
                ('states', models.ManyToManyField(related_name='story', to='rpgpt.storystate')),
            ],
        ),
    ]
