# Generated by Django 4.2.1 on 2023-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
